### ISSUE TITLE
How to set identity token and access token timeout in run time

### ISSUE THREAD

**Issue by vrrenga123** [DuendeSoftware/Samples#127] opened 2023-06-26 05:55 UTC
I am using Identity Server 6 with my ASP.NET Core. It is working fine. I tried to set the Access Token lifetime based on the roles in run time but it always take database configured value, it's not overwriting the run time value

[Img -1]
![image](https://github.com/DuendeSoftware/Samples/assets/31138666/3e21b130-856d-4dc9-a044-0926ad622a05)

[Img -2]

![image](https://github.com/DuendeSoftware/Samples/assets/31138666/cf56ed13-46de-4f27-ae36-3f27d834d1dd)

I tried to set in both places Login and GetProfileDataAsync but its not working as expected.

Is there any reason for this behavior?

**Comment by josephdecock** [comment] 2023-06-27 02:15
Duplicate of https://github.com/DuendeSoftware/Support/issues/731

**Closed by josephdecock** 2023-06-27 02:15 UTC
